# Generated by Django 4.2.10 on 2025-12-03 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.FileField(upload_to='products/images/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product')),
                ('variant', models.ForeignKey(blank=True, help_text='Link image to specific color variant', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.productvariant')),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
            },
        ),
    ]
