# Generated by Django 4.2.10 on 2025-12-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='instagram_link',
            field=models.CharField(blank=True, default='', help_text='Instagram username or profile link', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, default='', help_text='WhatsApp number for customer support', max_length=20),
        ),
    ]
